apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-captcha.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-captcha.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}